-- MySQL Script generated by MySQL Workbench
-- sáb 03 mai 2025 20:13:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplinas` (
  `id_disciplinas` INT NOT NULL,
  `nome_disciplina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_disciplinas`),
  UNIQUE INDEX `id_disciplinas_UNIQUE` (`id_disciplinas` ASC) VISIBLE,
  UNIQUE INDEX `nome_disciplina_UNIQUE` (`nome_disciplina` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `id_professor` INT NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(30) NULL,
  `id_disciplinas` INT NOT NULL,
  `status` VARCHAR(15) NULL,
  PRIMARY KEY (`id_professor`, `id_disciplinas`),
  UNIQUE INDEX `id_professor_UNIQUE` (`id_professor` ASC) VISIBLE,
  INDEX `fk_professor_disciplinas1_idx` (`id_disciplinas` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE,
  CONSTRAINT `fk_professor_disciplinas1`
    FOREIGN KEY (`id_disciplinas`)
    REFERENCES `mydb`.`disciplinas` (`id_disciplinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `id_endereco` INT NOT NULL,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(20) NULL,
  `cep` VARCHAR(10) NULL,
  `povoado` VARCHAR(30) NULL,
  `complemento` VARCHAR(45) NULL,
  `id_professor` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_endereco_professor1_idx` (`id_professor` ASC) VISIBLE,
  UNIQUE INDEX `complemento_UNIQUE` (`complemento` ASC) VISIBLE,
  UNIQUE INDEX `id_endereco_UNIQUE` (`id_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_professor1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `mydb`.`professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma` (
  `id_turma` INT NOT NULL,
  `nome` VARCHAR(35) NULL,
  `turno` VARCHAR(10) NULL,
  `ano_letivo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_turma`),
  UNIQUE INDEX `id_turma_UNIQUE` (`id_turma` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `id_aluno` INT NOT NULL,
  `nome_aluno` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `id_endereco` INT NOT NULL,
  `telefone` VARCHAR(15) NULL,
  `email` VARCHAR(30) NULL,
  `status` VARCHAR(15) NULL,
  `id_turma` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  INDEX `fk_aluno_endereco_idx` (`id_endereco` ASC) VISIBLE,
  UNIQUE INDEX `id_aluno_UNIQUE` (`id_aluno` ASC) VISIBLE,
  INDEX `fk_aluno_turma1_idx` (`id_turma` ASC) VISIBLE,
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_endereco`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `mydb`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `mydb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`boletim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`boletim` (
  `id_boletim` INT NOT NULL,
  `media_unidade_1` DECIMAL(4,2) NULL,
  `media_unidade_2` DECIMAL(4,2) NULL,
  `media_unidade_3` DECIMAL(4,2) NULL,
  `media_unidade_4` DECIMAL(4,2) NULL,
  `observacoes` TEXT(5000) NULL,
  `status` VARCHAR(15) NULL,
  `id_aluno` INT NOT NULL,
  `id_disciplinas` INT NOT NULL,
  PRIMARY KEY (`id_boletim`, `id_aluno`),
  UNIQUE INDEX `id_boletim_UNIQUE` (`id_boletim` ASC) VISIBLE,
  INDEX `fk_boletim_aluno1_idx` (`id_aluno` ASC) VISIBLE,
  INDEX `fk_boletim_disciplinas1_idx` (`id_disciplinas` ASC) VISIBLE,
  CONSTRAINT `fk_boletim_aluno1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `mydb`.`aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boletim_disciplinas1`
    FOREIGN KEY (`id_disciplinas`)
    REFERENCES `mydb`.`disciplinas` (`id_disciplinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`responsaveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`responsaveis` (
  `id_responsaveis` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_responsaveis`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma_disciplina_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma_disciplina_professor` (
  `id_turma` INT NOT NULL,
  `id_disciplinas` INT NOT NULL,
  `ano_letivo` INT NULL,
  `dia_aula` VARCHAR(15) NULL,
  `horario` TIME NULL,
  `id_professor` INT NOT NULL,
  INDEX `fk_turma_disciplina_professor_turma1_idx` (`id_turma` ASC) VISIBLE,
  INDEX `fk_turma_disciplina_professor_disciplinas1_idx` (`id_disciplinas` ASC) VISIBLE,
  INDEX `fk_turma_disciplina_professor_professor1_idx` (`id_professor` ASC) VISIBLE,
  CONSTRAINT `fk_turma_disciplina_professor_turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `mydb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_disciplina_professor_disciplinas1`
    FOREIGN KEY (`id_disciplinas`)
    REFERENCES `mydb`.`disciplinas` (`id_disciplinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_disciplina_professor_professor1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `mydb`.`professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno_responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno_responsavel` (
  `id_aluno_responsavel` INT NOT NULL,
  `parentesco` VARCHAR(15) NULL,
  `id_responsaveis` INT NOT NULL,
  `id_aluno` INT NOT NULL,
  PRIMARY KEY (`id_aluno_responsavel`, `id_aluno`),
  INDEX `fk_aluno_responsavel_responsaveis1_idx` (`id_responsaveis` ASC) VISIBLE,
  INDEX `fk_aluno_responsavel_aluno1_idx` (`id_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_responsavel_responsaveis1`
    FOREIGN KEY (`id_responsaveis`)
    REFERENCES `mydb`.`responsaveis` (`id_responsaveis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_responsavel_aluno1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `mydb`.`aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
